int: 0, 1, 3....
float: 34.5, 25.236
bool: True or False
Str: X = "Welcome to S4F Training" - object
complex: 3 + 4j

In [1]:
x = ["India", 1947, "Delhi", 200]
x

['India', 1947, 'Delhi', 200]

In [2]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [3]:
x.append("Karnataka")
x

['India', 1947, 'Delhi', 200, 'Karnataka']

In [4]:
x.insert(0, "Independence")
x

['Independence', 'India', 1947, 'Delhi', 200, 'Karnataka']

In [5]:
x.reverse()
x

['Karnataka', 200, 'Delhi', 1947, 'India', 'Independence']

In [6]:
# Strip cases
y = "19M"
a = y.rstrip("M")
int(a)

19

In [7]:
x[3]

1947

In [8]:
x[1:3]

[200, 'Delhi']

In [9]:
len(x)

6

In [10]:
t = ("Raghunandan", 12, "Mysuru")

In [11]:
type(t)

tuple

In [12]:
dir(tuple)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [13]:
# Dictionary - k:v
d1 = {"id":101, "name":"India", "age":200, "city":"Delhi"}
d1

{'id': 101, 'name': 'India', 'age': 200, 'city': 'Delhi'}

In [14]:
d1["name"]

'India'

In [15]:
d1.get("name")

'India'

In [16]:
del d1["city"]

In [17]:
d1

{'id': 101, 'name': 'India', 'age': 200}

In [18]:
s1 = {1, 4, 7, 9, 12}
s2 = {4, 6, 12, 8, 15}

In [19]:
s1.union(s2)

{1, 4, 6, 7, 8, 9, 12, 15}

In [20]:
s1.intersection(s2)

{4, 12}

In [21]:
# List comprehension - without
data = [23, 14, 56, 72, 90]
new_data = []
for x in data:
    if x%2==0:
        new_data.append(x)
new_data

[14, 56, 72, 90]

In [22]:
# If list comprehension is used!
data1 = [x for x in data if x%2==0]
data1

[14, 56, 72, 90]

In [23]:
pip install pandas numpy matplotlib seaborn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [24]:
import numpy as np

In [25]:
data = [23, 14, 56, 72, 90]
np.mean(data)

np.float64(51.0)

In [26]:
np.min(data)

np.int64(14)

In [27]:
a = [1, 3, 5, 6]
b = [4, 5, 6, 7]
arr1 = np.array(a)
arr2 = np.array(b)

In [29]:
arr2

array([4, 5, 6, 7])

In [30]:
arr1 * arr2

array([ 4, 15, 30, 42])

In [31]:
arr1.ndim

1

In [32]:
arr1.shape

(4,)

In [33]:
arr1.dtype

dtype('int64')

In [34]:
arr3 = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr3.ndim

2

In [36]:
arr3.shape

(3, 3)

In [37]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [39]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [40]:
np.random.randint(10, 100, 5)

array([79, 32, 92, 51, 98], dtype=int32)

In [41]:
np.random.uniform(10, 100, 50)

array([20.08256671, 94.28757626, 67.53498159, 12.75312621, 67.10494059,
       42.0131266 , 26.64969952, 18.14815627, 15.30272596, 84.28501568,
       12.27306833, 73.78817357, 11.1485257 , 47.19671248, 46.92913549,
       97.76084896, 45.59763969, 64.66387032, 69.29559955, 44.06786669,
       68.3007348 , 31.96196251, 56.12729033, 12.27024223, 62.18925671,
       43.61161547, 11.91704285, 82.47351473, 71.94377457, 79.8524967 ,
       74.04467926, 82.16730473, 87.54759203, 43.49531765, 43.35688853,
       96.01982712, 89.09076356, 92.6572079 , 20.96814262, 95.74852736,
       54.34056685, 99.44769212, 12.34786005, 61.10575551, 10.32251237,
       89.96582358, 57.21833197, 95.62573784, 37.87385153, 88.62835023])

In [43]:
np.random.rand(100)

array([0.39280539, 0.91011323, 0.91215924, 0.1954589 , 0.67085614,
       0.06412712, 0.57534473, 0.31603013, 0.2997589 , 0.72861739,
       0.91468248, 0.57840435, 0.09454272, 0.89670021, 0.74157423,
       0.46467119, 0.30351558, 0.24200573, 0.01539848, 0.38874529,
       0.06792536, 0.52104905, 0.73332514, 0.14249657, 0.00105586,
       0.87888843, 0.32897351, 0.75774973, 0.84181239, 0.42267463,
       0.46837274, 0.45796516, 0.90967604, 0.34819615, 0.67786277,
       0.5933439 , 0.6036819 , 0.78219359, 0.41574197, 0.20742166,
       0.70763745, 0.81168811, 0.59769316, 0.99408603, 0.48929394,
       0.80933488, 0.17735427, 0.8176812 , 0.43489794, 0.64882765,
       0.1509326 , 0.46077831, 0.18792895, 0.8127241 , 0.69836878,
       0.83230164, 0.1348143 , 0.10030472, 0.65500535, 0.27189723,
       0.71963184, 0.89903798, 0.99453336, 0.41788689, 0.57870785,
       0.51279604, 0.63945086, 0.78752336, 0.44021318, 0.4403575 ,
       0.67769705, 0.58094524, 0.80712779, 0.17335785, 0.79915

In [44]:
np.random.randint(10, 100, 12).reshape(4, 3)

array([[88, 97, 20],
       [13, 22, 67],
       [51, 87, 81],
       [15, 87, 53]], dtype=int32)

In [46]:
r = 45.7
np.floor(r)

np.float64(45.0)

In [47]:
np.ceil(r)

np.float64(46.0)

In [48]:
z = np.random.randint(1, 100, 12)

In [49]:
z = sorted(z)

In [50]:
z

[np.int32(8),
 np.int32(10),
 np.int32(20),
 np.int32(23),
 np.int32(25),
 np.int32(37),
 np.int32(42),
 np.int32(55),
 np.int32(70),
 np.int32(79),
 np.int32(89),
 np.int32(93)]

In [51]:
np.percentile(z, 75)

np.float64(72.25)

In [52]:
import pandas as pd

In [53]:
renewable_sources = ['Solar', 'Wind', 'Hydropower', 'Geothermal', 'Biomass']

data = {
    "Project":['Solar Farm', 'Wind Turbine', 'Hydropower', 'Solar Roof', 'Geothermal Plant'],
    "Technology":['Solar', 'Wind', 'Hydro', 'Solar', 'Geothermal'],
    "Capacity (MW)":[150, 300, 200, 50, 100],
    "Cost (Millions $)":[200, 400, 350, 100, 250],
    "Location":["California", "Texas", "Washington", "Nevada", "Chicago"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

In [54]:
# Create a pandas series for renewable energy sources
renewable_series = pd.Series(renewable_sources)
print("Renewable Energy Sources are:")
print(renewable_series)

Renewable Energy Sources are:
0         Solar
1          Wind
2    Hydropower
3    Geothermal
4       Biomass
dtype: object


In [56]:
# Create a DataFrame for green tech projects
df = pd.DataFrame(data)
print("Green Technology Projects DataFrame:")
print(df)

Green Technology Projects DataFrame:
            Project  Technology  Capacity (MW)  Cost (Millions $)    Location  \
0        Solar Farm       Solar            150                200  California   
1      Wind Turbine        Wind            300                400       Texas   
2        Hydropower       Hydro            200                350  Washington   
3        Solar Roof       Solar             50                100      Nevada   
4  Geothermal Plant  Geothermal            100                250     Chicago   

   Completion Year  
0             2023  
1             2024  
2             2022  
3             2025  
4             2023  


In [57]:
df['Project']

0          Solar Farm
1        Wind Turbine
2          Hydropower
3          Solar Roof
4    Geothermal Plant
Name: Project, dtype: object

In [58]:
print(df['Project'])

0          Solar Farm
1        Wind Turbine
2          Hydropower
3          Solar Roof
4    Geothermal Plant
Name: Project, dtype: object


In [59]:
df['Location']

0    California
1         Texas
2    Washington
3        Nevada
4       Chicago
Name: Location, dtype: object

In [60]:
# Want to print only high capacity projects (> 100 MW)
hcp = df[df['Capacity (MW)'] > 100]
hcp

Project Technology  Capacity (MW)  Cost (Millions $)    Location  \
0    Solar Farm      Solar            150                200  California   
1  Wind Turbine       Wind            300                400       Texas   
2    Hydropower      Hydro            200                350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022

In [61]:
df['Capacity (MW)'] > 100

0     True
1     True
2     True
3    False
4    False
Name: Capacity (MW), dtype: bool

In [62]:
# Add New Col
df["Cost per MW"] =df["Cost (Millions $)"] / df['Capacity (MW)']
df

Project  Technology  Capacity (MW)  Cost (Millions $)    Location  \
0        Solar Farm       Solar            150                200  California   
1      Wind Turbine        Wind            300                400       Texas   
2        Hydropower       Hydro            200                350  Washington   
3        Solar Roof       Solar             50                100      Nevada   
4  Geothermal Plant  Geothermal            100                250     Chicago   

   Completion Year  Cost per MW  
0             2023     1.333333  
1             2024     1.333333  
2             2022     1.750000  
3             2025     2.000000  
4             2023     2.500000

In [65]:
# Aggregation
total_capacity = df["Capacity (MW)"].sum()
total_cost = df["Cost (Millions $)"].sum()
print("The total Capacity of all the projects are: ", total_capacity)
print("The total cost of the projects: ", total_cost)

The total Capacity of all the projects are:  800
The total cost of the projects:  1300


In [66]:
# Grouping of data
grouped_data = df.groupby("Technology")["Capacity (MW)"].sum()
grouped_data

Technology
Geothermal    100
Hydro         200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64

## Day 3: Numpy

In [3]:
import numpy as np

energy_consumption = np.array([1200, 3400, 2900, 1800, 2500])
print("Energy consumption in mWh for different energy sources:")
energy_consumption

Energy consumption in mWh for different energy sources:


array([1200, 3400, 2900, 1800, 2500])

In [5]:
# Calculate the total energy consumption
total_consumption = np.sum(energy_consumption)
print(f'The total energy consumption is {total_consumption} MWh')

The total energy consumption is 11800 MWh


In [6]:
# Calculate the mean energy consumption
mean_consumption = np.mean(energy_consumption)
print(f'The mean energy consumption is {mean_consumption} MWh')

The mean energy consumption is 2360.0 MWh


In [7]:
# Calculate the standard deviation of energy consumption
std_ec = np.std(energy_consumption)
std_ec

np.float64(781.2809993849844)

In [8]:
print(f'The standard Deviation for Energy Consumption: {std_ec} MWh')

The standard Deviation for Energy Consumption: 781.2809993849844 MWh


In [9]:
# Reshape the array
reshaped_array = energy_consumption.reshape((5,1))
print('Reshaped array is:')
print(reshaped_array)

Reshaped array is:
[[1200]
 [3400]
 [2900]
 [1800]
 [2500]]


# Data Preprocessing

In [10]:
import pandas as pd
import numpy as np

# Sample data with missing values
data = {
    "Energy Source":['Solar', 'Wind', 'Hydropower', 'Geothermal', 'Biomass', 'Nuclear'],
    "Energy Consumption (MWh)":[1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (millions $)":[200, 400, np.nan, 150, 250, np.nan]
}

In [11]:
# Create a dataframe:
df = pd.DataFrame(data)
print(df)

  Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                    1200.0              200.0
1          Wind                       NaN              400.0
2    Hydropower                    2900.0                NaN
3    Geothermal                       NaN              150.0
4       Biomass                    2500.0              250.0
5       Nuclear                    3200.0                NaN


## Handle the missing values:
 - Removing (drop) mv
 - impute (fill) mv - mean

In [12]:
# Remove rows with missing value
cleaned_df = df.dropna()
cleaned_df

Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                    1200.0              200.0
4       Biomass                    2500.0              250.0

## Imputation - too add or fill
 - with mean
 - foward/backward filling

In [13]:
# Impute missing values with the mean for energy consumption
df['Energy Consumption (MWh)'].fillna(df['Energy Consumption (MWh)'].mean(), inplace=True)
df['Cost (millions $)'].fillna(df['Cost (millions $)'].mean(), inplace=True)

df

C:\Users\Raghunandan M S\AppData\Local\Temp\ipykernel_18672\2818430243.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Energy Consumption (MWh)'].fillna(df['Energy Consumption (MWh)'].mean(), inplace=True)
C:\Users\Raghunandan M S\AppData\Local\Temp\ipykernel_18672\2818430243.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on 

Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                    1200.0              200.0
1          Wind                    2450.0              400.0
2    Hydropower                    2900.0              250.0
3    Geothermal                    2450.0              150.0
4       Biomass                    2500.0              250.0
5       Nuclear                    3200.0              250.0

In [14]:
# Forward filling missing values
ff_df = df.fillna(method="ffill")
ff_df

C:\Users\Raghunandan M S\AppData\Local\Temp\ipykernel_18672\1748103493.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ff_df = df.fillna(method="ffill")


Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                    1200.0              200.0
1          Wind                    2450.0              400.0
2    Hydropower                    2900.0              250.0
3    Geothermal                    2450.0              150.0
4       Biomass                    2500.0              250.0
5       Nuclear                    3200.0              250.0

In [ ]:
pip install scikit-learn

In [17]:
# Data Preprocessing - Normalization
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['Energy Consumption (MWh)', 'Cost (millions $)']] = scaler.fit_transform(
    df[['Energy Consumption (MWh)', 'Cost (millions $)']])

df

Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                     0.000                0.2
1          Wind                     0.625                1.0
2    Hydropower                     0.850                0.4
3    Geothermal                     0.625                0.0
4       Biomass                     0.650                0.4
5       Nuclear                     1.000                0.4

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[['Energy Consumption (MWh)', 'Cost (millions $)']] = scaler.fit_transform(
    df[['Energy Consumption (MWh)', 'Cost (millions $)']])
df

Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar             -2.005893e+00      -6.546537e-01
1          Wind              3.563181e-16       1.963961e+00
2    Hydropower              7.221213e-01       1.817029e-16
3    Geothermal              3.563181e-16      -1.309307e+00
4       Biomass              8.023570e-02       1.817029e-16
5       Nuclear              1.203536e+00       1.817029e-16

## Encoding - one hot encoding

In [20]:
ohe_df = pd.get_dummies(df, columns=["Energy Source"])
print(ohe_df)

   Energy Consumption (MWh)  Cost (millions $)  Energy Source_Biomass  \
0             -2.005893e+00      -6.546537e-01                  False   
1              3.563181e-16       1.963961e+00                  False   
2              7.221213e-01       1.817029e-16                  False   
3              3.563181e-16      -1.309307e+00                  False   
4              8.023570e-02       1.817029e-16                   True   
5              1.203536e+00       1.817029e-16                  False   

   Energy Source_Geothermal  Energy Source_Hydropower  Energy Source_Nuclear  \
0                     False                     False                  False   
1                     False                     False                  False   
2                     False                      True                  False   
3                      True                     False                  False   
4                     False                     False                  False   
5       

In [21]:
# Feature engineering
ohe_df["Consumption per Million $"] = ohe_df['Energy Consumption (MWh)'] / ohe_df['Cost (millions $)']

ohe_df

Energy Consumption (MWh)  Cost (millions $)  Energy Source_Biomass  \
0             -2.005893e+00      -6.546537e-01                  False   
1              3.563181e-16       1.963961e+00                  False   
2              7.221213e-01       1.817029e-16                  False   
3              3.563181e-16      -1.309307e+00                  False   
4              8.023570e-02       1.817029e-16                   True   
5              1.203536e+00       1.817029e-16                  False   

   Energy Source_Geothermal  Energy Source_Hydropower  Energy Source_Nuclear  \
0                     False                     False                  False   
1                     False                     False                  False   
2                     False                      True                  False   
3                      True                     False                  False   
4                     False                     False                  False   
5                     False                     False                   True   

   Energy Source_Solar  Energy Source_Wind  Consumption per Million $  
0                 True               False               3.064052e+00  
1                False                True               1.814283e-16  
2                False               False               3.974187e+15  
3                False               False              -2.721424e-16  
4                False               False               4.415764e+14  
5                False               False               6.623646e+15